/* Handles operations related to user management */

// import dependencies
const bcrypt = require("bcrypt");
const jwt = require("jsonwebtoken");
const User = require("../models/User");
const Blog = require("../models/Blog");
const fs = require("fs");
const path = require("path");

// function to register a user
exports.register = async (req, res) => {
  try {
    // get the username and password and profilepic
    const { username, password, role } = req.body;
    const profilePicture = req.file.filename; // Use the file name generated by multer

    // Check if the username is already taken
    const existingUser = await User.findOne({ username });
    if (existingUser) {
      return res.status(400).json({ message: "Username is already taken" });
    }

    // Hash the password
    const hashedPassword = await bcrypt.hash(password, 10);

    // Create a new user
    const newUser = new User({
      username,
      password: hashedPassword,
      profilePicture,
      role,
    });
    // save the user in the database
    await newUser.save();

    // send success message
    res.status(201).json({ message: "User registered successfully" });
  } catch (error) {
    console.error(error); // Log the error to the console for debugging purposes
    // send error message
    res
      .status(500)
      .json({ message: "Internal server error", error: error.message });
  }
};

// function to handle the login of a user
exports.login = async (req, res) => {
  try {
    // get the username and password
    const { username, password } = req.body;

    // Check if the user exists
    const user = await User.findOne({ username });
    if (!user) {
      return res.status(401).json({ message: "Invalid username or password" });
    }

    // Compare the password
    const isPasswordValid = await bcrypt.compare(password, user.password);
    if (!isPasswordValid) {
      return res.status(401).json({ message: "Invalid username or password" });
    }

    // Generate a JWT token using the userId and the secret key
    const token = jwt.sign({ userId: user._id }, "my_secret_key");

    // send the token, userId, and role to be used in the frontend
    res.json({
      message: "User logged in successfully",
      token,
      userId: user._id,
      role: user.role,
    });
  } catch (error) {
    console.log(error);
    // send the error message
    res.status(500).json({ message: "Internal server error" });
  }
};

// function to get the logged in user's information
exports.getUser = async (req, res) => {
  try {
    // get the user ID
    const { userId } = req.params;

    if (!userId) {
      return res.status(400).json({ message: "Invalid userId" });
    }

    // Find the user by ID
    const user = await User.findById(userId);

    // if the user does not exist
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    // Return the user data
    res.json({ user });
  } catch (error) {
    console.error(error);
    // send the error message
    res
      .status(500)
      .json({ message: "Internal server error", error: error.message });
  }
};

// function to get all the users' information
exports.getUsers = async (req, res) => {
  try {
    // Find all users
    const users = await User.find();

    // if there are no users in the database
    if (users.length === 0) {
      return res.status(404).json({ message: "No users found" });
    }

    // Return the users
    res.json({ users });
  } catch (error) {
    console.error(error);
    res
      .status(500)
      .json({ message: "Internal server error", error: error.message });
  }
};

// function to allow the user to change their username
exports.changeUsername = async (req, res) => {
  try {
    // expects the user ID as a parameter
    const { userId } = req.params;
    // get the new username
    const { newUsername } = req.body;

    // Find the user by ID
    const user = await User.findById(userId);

    // if the user is not found
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    // Update the username
    user.username = newUsername;
    // save the user
    await user.save();

    // send success message
    res.json({ message: "Username updated successfully" });
  } catch (error) {
    console.error(error);
    // send error message
    res
      .status(500)
      .json({ message: "Internal server error", error: error.message });
  }
};

// function for user to change their password
exports.changePassword = async (req, res) => {
  try {
    // expects the user ID as a parameter
    const { userId } = req.params;
    // get the current and new password
    const { currentPassword, newPassword } = req.body;

    // Find the user by ID
    const user = await User.findById(userId);

    // if the user is not found
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    // Compare the current password
    const isPasswordValid = await bcrypt.compare(
      currentPassword,
      user.password
    );
    // if the current password input does not match the password in the database
    if (!isPasswordValid) {
      return res.status(401).json({ message: "Invalid current password" });
    }

    // Hash the new password
    const hashedPassword = await bcrypt.hash(newPassword, 10);

    // Update the password
    user.password = hashedPassword;
    // save the user
    await user.save();

    // send success message
    res.json({ message: "Password updated successfully" });
  } catch (error) {
    console.error(error);
    // send error message
    res
      .status(500)
      .json({ message: "Internal server error", error: error.message });
  }
};

// function to change user profile picture
exports.changeProfilePicture = async (req, res) => {
  try {
    // expects the user ID as a parameter
    const { userId } = req.params;
    // get the new profile picture file
    const profilePicture = req.file.filename;

    // Find the user by ID
    const user = await User.findById(userId);

    // if the user is not in the database
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    // delete the previous profile picture in the folder
    const previousProfilePic = user.profilePicture;
    if (previousProfilePic) {
      const profilePicsPath = path.join(
        __dirname,
        "../ProfilePics",
        previousProfilePic
      );
      fs.unlinkSync(profilePicsPath);
    }

    // Update the profile picture
    user.profilePicture = profilePicture;
    // save the user
    await user.save();
    // send the success message
    res.json({ message: "Profile picture updated successfully" });
  } catch (error) {
    console.error(error);
    // send error message
    res
      .status(500)
      .json({ message: "Internal server error", error: error.message });
  }
};

// function to delete the user's own account
exports.deleteAccount = async (req, res) => {
  try {
    const { userId } = req.params;

    // Retrieve user's blogs
    const userBlogs = await Blog.find({ user: userId });

    // Delete the blog images
    userBlogs.forEach((blog) => {
      const imagePath = path.join(__dirname, "../uploads", blog.image);
      fs.unlinkSync(imagePath);
    });

    // Retrieve user's profile picture
    const user = await User.findById(userId);
    const profilePicturePath = path.join(
      __dirname,
      "../profilePics",
      user.profilePicture
    );
    fs.unlinkSync(profilePicturePath);

    // Delete user's blog posts
    await Blog.deleteMany({ user: userId });

    // Delete the user
    await User.findByIdAndDelete(userId);

    res.status(200).json({ message: "Account deleted successfully" });
  } catch (error) {
    console.error(error);
    res
      .status(500)
      .json({ message: "An error occurred while deleting the account" });
  }
};
